let switchTab = document.querySelectorAll('.head .switch span') ;
switchTab[0].onclick = function() {
  switchTab[0].style.display = 'none' ;
  switchTab[1].style.display = 'block' ;
  document.documentElement.style.setProperty('--theme-body-color', 'hsl(0,0%,90%)');
  document.documentElement.style.setProperty('--theme-text-color', 'hsl(60,10%,19%)');
  document.documentElement.style.setProperty('--theme-screen-color', 'hsl(0,0%,93%)');
  document.documentElement.style.setProperty('--theme-keypad-color', 'hsl(0,5%,81%)');
  document.documentElement.style.setProperty('--theme-keys-num-color', 'hsl(60, 10%, 19%)');
  document.documentElement.style.setProperty('--theme-keys-color', 'hsl(45,7%,89%)');
  document.documentElement.style.setProperty('--theme-keys-shadow-color', 'hsl(35,11%,61%)');
  document.documentElement.style.setProperty('--theme-del-reset-keys-color', 'hsl(185,42%,37%)');
  document.documentElement.style.setProperty('--theme-del-reset-keys-shadow-color', 'hsl(185,58%,25%)');
  document.documentElement.style.setProperty('--theme-equal-keys-color', 'hsl(25,98%,40%)');
  document.documentElement.style.setProperty('--theme-equal-keys-shadow-color', 'hsl(25,99%,27%)');
  switchTab[1].parentNode.style.backgroundColor = 'hsl(0,5%,81%)' ;
  switchTab[2].style.display = 'none';
};
switchTab[1].onclick = function() {
  switchTab[0].style.display = 'none';
  switchTab[1].style.display = 'none';
  switchTab[2].style.display = 'block';
  switchTab[2].parentNode.style.backgroundColor = 'hsl(268,71%,12%)' ;
  document.documentElement.style.setProperty('--theme-body-color', 'hsl(268, 75%, 9%)');
  document.documentElement.style.setProperty('--theme-text-color', 'hsl(52, 100%, 62%)');
  document.documentElement.style.setProperty('--theme-screen-color', 'hsl(268, 71%, 12%)');
  document.documentElement.style.setProperty('--theme-keypad-color', 'hsl(268, 71%, 12%)');
  document.documentElement.style.setProperty('--theme-keys-num-color', 'hsl(52, 100%, 62%)');
  document.documentElement.style.setProperty('--theme-keys-color', 'hsl(268, 47%, 21%)');
  document.documentElement.style.setProperty('--theme-keys-shadow-color', 'hsl(290, 70%, 36%)');
  document.documentElement.style.setProperty('--theme-del-reset-keys-color', 'hsl(281, 89%, 26%)');
  document.documentElement.style.setProperty('--theme-del-reset-keys-shadow-color', 'hsl(285, 91%, 52%)');
  document.documentElement.style.setProperty('--theme-equal-keys-color', 'hsl(176, 100%, 44%)');
  document.documentElement.style.setProperty('--theme-equal-keys-shadow-color', 'hsl(177, 92%, 70%)');
  document.documentElement.style.setProperty('--theme-equal-keys-con-color', '#000');
};
switchTab[2].onclick = function() {
  switchTab[0].style.display = 'block';
  document.documentElement.style.setProperty('--theme-body-color', 'hsl(222,26%,31%)');
  document.documentElement.style.setProperty('--theme-text-color', '#FFF');
  document.documentElement.style.setProperty('--theme-screen-color', 'hsl(224,36%,15%)');
  document.documentElement.style.setProperty('--theme-keypad-color', 'hsl(223,31%,20%)');
  document.documentElement.style.setProperty('--theme-keys-num-color', 'hsl(221, 14%, 31%)');
  document.documentElement.style.setProperty('--theme-keys-color', 'hsl(30,25%,89%)');
  document.documentElement.style.setProperty('--theme-keys-shadow-color', 'hsl(28,16%,65%)');
  document.documentElement.style.setProperty('--theme-del-reset-keys-color', 'hsl(225, 21%, 49%)');
  document.documentElement.style.setProperty('--theme-del-reset-keys-shadow-color', 'hsl(224,28%,35%)');
  document.documentElement.style.setProperty('--theme-equal-keys-color', 'hsl(6,63%,50%)');
  document.documentElement.style.setProperty('--theme-equal-keys-shadow-color', 'hsl(6,70%,34%)');
  document.documentElement.style.setProperty('--theme-equal-keys-con-color', '#FFF');
  switchTab[1].style.display = 'none';
  switchTab[2].style.display = 'none';
};